### ISSUE TITLE
Add Testimonials

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/django-best-practices#5]
> A great overview of best practices in developing and deploying with Django. Bookmarked.

[Smashing Magazine](https://twitter.com/smashingmag/status/246662272536154112)

> If you're a web developer, you should know about this.

[Mike Loukides](https://twitter.com/mikeloukides/status/246189099814379520)

> This is close to being a direct channel to my brain. Perfect!

[Daniel Greenfeld (pydanny)](http://news.ycombinator.com/item?id=4515458)

**Comment by mtrythall** [comment]
Where is this stuff going to go? It's awesome to have it, but I don't want to take away from the reading experience if we can help it.

**Comment by ipmb** [comment]
I think the first page can serve more as a book cover/preface than meaty content. Patches welcome :)
